### ISSUE TITLE
webServer.py starts but is not responding on port 5000

### ISSUE THREAD

**Issue by yauh** [adeept/Adeept_RaspTank#20]
I have cloned the repo on Dec 26 2020 and ran into issues. I have a fully assembled RaspTank (powered by micro USB adaptor on Raspberry Pi 3b+, no batteries.
When I run boot the Raspberry the web interface does not become available so I followed instructions.
killall python3 and manually started the `webServer.py` as sudo. The following was shown:

```pi@raspberrypi:~/adeept_rasptank/server $ sudo python3 webServer.py 
......................pause..........................
Starting camera thread.
OLED disconnected
OLED没有连接
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/adeept_rasptank/server/OLED.py", line 49, in run
    with canvas(device) as draw:
NameError: name 'device' is not defined

......................pause..........................
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
192.168.0.96
waiting for connection...
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

With netstat I made sure something was listening

```pi@raspberrypi:~ $ sudo netstat -pant
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      1026/python3        
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      1026/python3  
```

Trying to access the web site with Google Chrome ran into a timeout/no reply.
A couple of questions:
1) Is there any way to increase logging/debug info to pinpoint the error?
2) As there was no OLED component I would expect no error to be thrown by a missing OLED screen.
3) Could it be that the power supply is too weak and therefore I cannot get an answer by the web server on port 5000 (I doubt it, but maybe it's somehow connected)?

side LEDs of the RaspTank are blinking in blue, so some power is available.

**Comment by yauh** [comment]
As I feared, once I used the correct batteries there are no more issues. Sorry for the false alert.
