### ISSUE TITLE
no running event loop loop issue

### ISSUE THREAD

**Issue by cheekybeakyweeky** [adeept/Adeept_RaspTank#40]
![image](https://github.com/user-attachments/assets/15597b89-6c55-49e3-aa0d-fb41b02111df)

image provided, followed all steps, manually upgraded openCV. 
Any idea on how to fix?
it repeats 
192.168.0.99
no running event loop

until ctrl copy
```
......................pause..........................
Starting camera thread.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage O  penCV | GStreamer warning: Embedded video playback halted; module v4l2src0 repor  ted: Cannot identify device '/dev/video-1'.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GS  treamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlayin  g OpenCV | GStreamer warning: GStreamer: pipeline have not been created
OLED disconnected
OLED没有连接
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/eswan/adeept_rasptank/server/OLED.py", line 49, in run
    with canvas(device) as draw:
NameError: name 'device' is not defined
......................pause..........................
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployme  nt.
192.168.0.99
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
no running event loop
192.168.0.99
no running event loop
```

**Comment by adeept** [comment]
Hello,

If there is no "waiting for connection..." message after weServer.Py runs, as shown in the figure below, but it keeps displaying "no running event loop 192.168.0.99 no running events loop", then this problem is caused by unstable network configuration, and you need to successfully configure the Raspberry Pi's self startup settings. Next, please refer to the "3.4 Starting Raspberry Pi OS" section in "Lesson 3 Installing and Configuring Raspberry Pi OS. pdf", but this time we need to do the opposite: turn off the Wi Fi function of Raspberry Pi. The purpose of doing this is not to access and control the robot through SSH, but after restarting the Raspberry Pi, you should be able to access its web interface through a browser to operate the robot.
 



Under normal circumstances, if the robot program is not connected to WIFI during the connection process
After opening, it will automatically turn on the hotspot. You can use your phone or computer
Search for WIF named Adeept_Sobot. The default password is 12345678. once
After successful connection, you can log in to 192.168.12.1:5000 and open it using a browser
Use web applications to control robots.




If it fails, you will need to replace the SD card and re burn the Raspberry Pi system.







Best!
------------------------------------------
Adeept Tech Support Team
Adeept Technology Co., Ltd.
E-mail: ***@***.***
Web: www.adeept.com










---- Replied Message ----
From ***@***.***> Date 12/2/2024 06:52 To ***@***.***> Cc ***@***.***> Subject [adeept/Adeept_RaspTank] no running event loop loop issue (Issue #40)  
image.png (view on web)
image provided, followed all steps, manually upgraded openCV.
 Any idea on how to fix?
 it repeats
 192.168.0.99
 no running event loop
until ctrl copy
......................pause..........................
Starting camera thread.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage O  penCV | GStreamer warning: Embedded video playback halted; module v4l2src0 repor  ted: Cannot identify device '/dev/video-1'.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GS  treamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlayin  g OpenCV | GStreamer warning: GStreamer: pipeline have not been created
OLED disconnected
OLED没有连接
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/eswan/adeept_rasptank/server/OLED.py", line 49, in run
    with canvas(device) as draw:
NameError: name 'device' is not defined
......................pause..........................
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployme  nt.
192.168.0.99
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
no running event loop
192.168.0.99
no running event loop

**Comment by adeept** [comment]
Hello,

The self startup setting in Raspberry Pi refers to the process of configuring the Pi to automatically execute specific programs or scripts when turned on. SSH requires a Wi Fi connection to use, but now you need to disconnect the Wi Fi to run webServer. py, so SSH cannot be used. You need to set the self startup settings so that webServer. py automatically executes when booting up, and at this time, Raspberry Pi will turn on the hotspot.


Before disconnecting the WiFi, you need to configure the self startup. The tutorial on configuring self startup can be found in section 3 In the "Lesson 12 Configuring Auto run Program. pdf" directory under "Basic course". And you also need to open i2c. Here are the steps to open i2c


sudo raspi-config
Select '3 Interface Options'
Select 'P5 I2C'
Select 'Yes' to open i2c




Under normal circumstances, if the robot program is not connected to WIFI during the connection process
After opening, it will automatically turn on the hotspot. You can use your phone or computer
Search for WIF named Adeept_Sobot. The default password is 12345678. once
After successful connection, you can log in to 192.168.12.1:5000 and open it using a browser
Use web applications to control robots.


If the WiFi cannot be disconnected according to the previously provided method, another way is to turn off or move the WiFi signal source connected to the Raspberry Pi, so that the Raspberry Pi cannot connect to the WiFi network.



Best!
------------------------------------------
Adeept Tech Support Team
Adeept Technology Co., Ltd.
E-mail: ***@***.***
Web: www.adeept.com










---- Replied Message ----
From ***@***.***> Date 12/2/2024 06:52 To ***@***.***> Cc ***@***.***> Subject [adeept/Adeept_RaspTank] no running event loop loop issue (Issue #40)  
image.png (view on web)
image provided, followed all steps, manually upgraded openCV.
 Any idea on how to fix?
 it repeats
 192.168.0.99
 no running event loop
until ctrl copy
......................pause..........................
Starting camera thread.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage O  penCV | GStreamer warning: Embedded video playback halted; module v4l2src0 repor  ted: Cannot identify device '/dev/video-1'.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GS  treamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlayin  g OpenCV | GStreamer warning: GStreamer: pipeline have not been created
OLED disconnected
OLED没有连接
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/eswan/adeept_rasptank/server/OLED.py", line 49, in run
    with canvas(device) as draw:
NameError: name 'device' is not defined
......................pause..........................
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployme  nt.
192.168.0.99
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
no running event loop
192.168.0.99
no running event loop
